### ISSUE TITLE
account-password-policy.yaml failed to deploy

### ISSUE THREAD

**Issue by reidca** [widdix/aws-cf-templates#148]
TemplateID: security/account-password-policy
Region: eu-west-1

Deploying this stack using all default parameter values fails with DELETE_FAILED. Checking the events in more detail:

CREATE_FAILED | Custom::PasswordPolicy | PasswordPolicy | Custom Resource failed to stabilize in expected time

I don't know whether this is an environment issue however as I said, all parameters were left as default and no changes were made to the template.

**Comment by michaelwittig** [comment]
Hi @reidca 
in CLoudWatch Logs, you will find a log group (`/lambda/...`) for the lambda resource that implements the custom resource. Can you copy the relevant log lines to the issue?

**Comment by reidca** [comment]
START RequestId: 5ecc5b14-029a-11e8-a75d-6b7c573908f6 Version: $LATEST
Syntax error in module 'index': SyntaxError
} else if (event.RequestType === 'Create' ||��event.RequestType === 'Update') {
^
SyntaxError: Invalid or unexpected token
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
END RequestId: 5ecc5b14-029a-11e8-a75d-6b7c573908f6
REPORT RequestId: 5ecc5b14-029a-11e8-a75d-6b7c573908f6	Duration: 8.51 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 20 MB	
START RequestId: 5ecc5b14-029a-11e8-a75d-6b7c573908f6 Version: $LATEST
Syntax error in module 'index': SyntaxError
^
SyntaxError: Invalid or unexpected token
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
END RequestId: 5ecc5b14-029a-11e8-a75d-6b7c573908f6
REPORT RequestId: 5ecc5b14-029a-11e8-a75d-6b7c573908f6	Duration: 18.27 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 20 MB	
START RequestId: 5ecc5b14-029a-11e8-a75d-6b7c573908f6 Version: $LATEST
Syntax error in module 'index': SyntaxError
SyntaxError: Invalid or unexpected token
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
END RequestId: 5ecc5b14-029a-11e8-a75d-6b7c573908f6
REPORT RequestId: 5ecc5b14-029a-11e8-a75d-6b7c573908f6	Duration: 13.68 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 20 MB

**Comment by reidca** [comment]
Looks like a couple of extraneous characters have slipped into the script from somewhere! I will remove them and try again.

**Comment by reidca** [comment]
Apologies, now working. It was the odd characters that came into the template when copying and pasting. I did it in raw this time. Sorry for wasting your time.
