### ISSUE TITLE
wordpress/wordpress-ha upgrade issues: existing lock directory and ToolError: Could not enable service amazon-ssm-agent (return code 1)

### ISSUE THREAD

**Issue by ismailyenigul** [widdix/aws-cf-templates#444]
Region: us-east-1

We were running WP with your wordpress/wordpress-ha  template version 0.8
I tried to upgrade the latest version(12.2), Cloudformation deployment was always failing.
When I check the logs on the failing instances and cloudwatch, I found the issues.

1. /var/www/locks directory exist and wp deployment fails.
/root/wordpres.sh has the following check
```
if mkdir /var/www/lock; then
  cd /var/www/html

```
The template returns mkdir: cannot create directory ‘ /var/www/lock’: File exists
So anyone who wants to upgrade the stack, first must delete lock directory.
It is better to mention this in the deployment guide.

The second issue is enabling aws-ssm-agent
It never works. Always fails with the following error

```
20-05-19 22:02:02,386 [DEBUG] Using service modifier: /sbin/chkconfig
2020-05-19 22:02:02,386 [DEBUG] Setting service amazon-ssm-agent to enabled
2020-05-19 22:02:02,391 [ERROR] chkconfig failed with error 1. Output: Note: Forwarding request to 'systemctl enable amazon-ssm-agent.service'.
Failed to execute operation: File exists

2020-05-19 22:02:02,392 [ERROR] Error encountered during build of config: Could not enable service amazon-ssm-agent (return code 1)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 270, in build
    CloudFormationCarpenter._serviceTools[manager]().apply(services, changes)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 155, in apply
    self._set_service_enabled(service, util.interpret_boolean(serviceProperties["enabled"]))
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 234, in _set_service_enabled
    modifier.set_service_enabled(service, enabled);
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 297, in set_service_enabled
    raise ToolError("Could not %s service %s" % ("enable" if enabled else "disable", service), result.returncode)
ToolError: Could not enable service amazon-ssm-agent (return code 1)
2020-05-19 22:02:02,394 [ERROR] -----------------------BUILD FAILED!------------------------
2020-05-19 22:02:02,394 [ERROR] Unhandled exception during build: Could not enable service amazon-ssm-agent (return code 1)
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 270, in build
    CloudFormationCarpenter._serviceTools[manager]().apply(services, changes)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 155, in apply
    self._set_service_enabled(service, util.interpret_boolean(serviceProperties["enabled"]))
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 234, in _set_service_enabled
    modifier.set_service_enabled(service, enabled);
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 297, in set_service_enabled
    raise ToolError("Could not %s service %s" % ("enable" if enabled else "disable", service), result.returncode)
ToolError: Could not enable service amazon-ssm-agent (return code 1)
2020-05-19 22:02:02,653 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
2020-05-19 22:02:02,654 [DEBUG] Signaling resource AutoScalingGroup in stack wordpress with unique ID i-xxx and status FAILURE
May 19 22:02:02 cloud-init[2670]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
May 19 22:02:02 cloud-init[2670]: util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
Traceback (most recent call last):
  File "/usr/lib/pyt
```

I had to set `HasSystemsManagerAccess: false` to deploy CF stack successfully
I do not know what is wrong with` systemctl enable amazon-ssm-agent.service`
It works fine when I ssh to the instance and run it manually.

**Comment by andreaswittig** [comment]
Thanks for reporting that issue. Have heard about similar problems from someone else. Could you please provide the details, as well as the exact template id and version that you are using here?

**Comment by ismailyenigul** [comment]
Hello,

I use this wordpress/wordpress-ha from   https://github.com/widdix/aws-cf-templates/tree/v12.2.0

Thanks

**Comment by michaelwittig** [comment]
hi @ismailyenigul  do you try to update from 0.8 to 12.1 ? we only provide migration paths from the previous version to the next. e.g. from 11.y.z to 12.y.z.

**Comment by ismailyenigul** [comment]
yes i upgrade from 0.8 to 12.1
but I believe it is not an issue. It is clearly related to ssm-agent deployment.
I disabled it and it worked.

**Comment by michaelwittig** [comment]
I'm happy to hear that the update worked more or less in your case. The first issue regarding the lock file is very likely caused by skipping 11 major versions. I will not focus on that.

The second issue sounds more interesting. I can not reproduce the issue. We start at least three stacks with `WebServerSystemsManagerAccess:=true` for testing in different regions per week and it works. The question is: what's different with your setup.

Can you share a screenshot/list of the parameters and values you use?

Could you check if you can find logs in CloudWatch Logs under `<INSTANCEID>/var/log/amazon/ssm/amazon-ssm-agent.log`?

**Comment by HaiCheViet** [comment]
For me, the same issue appear on https://github.com/widdix/aws-cf-templates/blob/master/vpc/vpc-ssh-bastion.yaml and vpc-vpn-bastion. Even I fresh init VPC service and bastion, the service still not work (It worked two weeks ago). 
The log file ec2 setup said they can't enable the service amazon-ssm-agent. After I disable SystemsManagerAccess the system work properlyy

**Comment by michaelwittig** [comment]
@HaiCheViet Have you also upgraded? If so, what was the old version? And what is the version you updated to?

**Comment by michaelwittig** [comment]
closed due to inactivity
