### ISSUE TITLE
Restoring a Backup sends failure signal to Cloudformation

### ISSUE THREAD

**Issue by shotty1** [widdix/aws-cf-templates#504]
TemplateID: ec2/al2-mutable-private.yaml
TemplateVersion: 12.11.0
Region: eu-central-1
AL2 Version: 20191217.0

When restoring a mutable EC2 from Backup you get a failure signal because when enabling services that are already enabled (see error below.)

A workaround is temporarily removing the CreationPolicy from the template.

I do not have a good idea on how to solve this since it is a bug in cfn-init that doesn't handle enabling services that are already enabled via sysvinit correctly. Maybe just document it for now?

```
020-11-01 14:20:36,579 [ERROR] Unhandled exception during build: Could not enable service amazon-ssm-agent (return code 1)
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 270, in build
    CloudFormationCarpenter._serviceTools[manager]().apply(services, changes)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 155, in apply
    self._set_service_enabled(service, util.interpret_boolean(serviceProperties["enabled"]))
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 234, in _set_service_enabled
    modifier.set_service_enabled(service, enabled);
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 297, in set_service_enabled
    raise ToolError("Could not %s service %s" % ("enable" if enabled else "disable", service), result.returncode)
ToolError: Could not enable service amazon-ssm-agent (return code 1)
2020-11-01 14:20:36,819 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.eu-central-1.amazonaws.com
2020-11-01 14:20:36,819 [DEBUG] Signaling resource VirtualMachine in stack mycoolstack-ec2-mutable-private-a-v2 with unique ID i-123456789123456789 and status FAILURE
```

**Comment by michaelwittig** [comment]
I can't reproduce the issue you describe. Do you have access to the cfn-init logs when you remove the CreationPolicy?

**Comment by shotty1** [comment]
Not reproducible any more. Will check again if the error occurs again.
